// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class Materia
    {
        public Materia()
        {
            tbMaestrosPorCursos = new HashSet<tbMaestrosPorCursos>();
            tbReportesPorMaestros = new HashSet<tbReportesPorMaestros>();
        }

        public int Mate_Id { get; set; }
        public string Mate_Descripcion { get; set; }
        public int? Mate_Creacion { get; set; }
        public DateTime? Mate_FechaCreacion { get; set; }
        public int? Mate_Modificacion { get; set; }
        public DateTime? Mate_FechaModificacion { get; set; }
        public bool? Mate_Estado { get; set; }

        public virtual tbUsuarios Mate_CreacionNavigation { get; set; }
        public virtual tbUsuarios Mate_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMaestrosPorCursos> tbMaestrosPorCursos { get; set; }
        public virtual ICollection<tbReportesPorMaestros> tbReportesPorMaestros { get; set; }
    }
}