// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbAlumnos
    {
        public tbAlumnos()
        {
            tbCalificacionPorAlumno = new HashSet<tbCalificacionPorAlumno>();
            tbPadresPorAlumno = new HashSet<tbPadresPorAlumno>();
            tbReportesPorMaestros = new HashSet<tbReportesPorMaestros>();
        }

        public int Alum_Id { get; set; }
        public int? Pers_Id { get; set; }
        public int? Curs_Id { get; set; }
        public int? Matr_Id { get; set; }
        public int? Alum_Creacion { get; set; }
        public DateTime? Alum_FechaCreacion { get; set; }
        public int? Alum_Modificacion { get; set; }
        public DateTime? Alum_FechaModificacion { get; set; }
        public bool? Alum_Estado { get; set; }

        public virtual tbUsuarios Alum_CreacionNavigation { get; set; }
        public virtual tbUsuarios Alum_ModificacionNavigation { get; set; }
        public virtual tbCursos Curs { get; set; }
        public virtual tbMatricula Matr { get; set; }
        public virtual ICollection<tbCalificacionPorAlumno> tbCalificacionPorAlumno { get; set; }
        public virtual ICollection<tbPadresPorAlumno> tbPadresPorAlumno { get; set; }
        public virtual ICollection<tbReportesPorMaestros> tbReportesPorMaestros { get; set; }
    }
}