// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbCalificacionPorAlumno
    {
        public int CapA_Id { get; set; }
        public int? Alum_Id { get; set; }
        public int? Mate_Id { get; set; }
        public int? Maes_Id { get; set; }
        public decimal? CapA_Calficacion { get; set; }
        public int? CapA_Creacion { get; set; }
        public DateTime? CapA_FechaCreacion { get; set; }
        public int? CapA_Modificacion { get; set; }
        public DateTime? CapA_FechaModificacion { get; set; }
        public bool? CapA_Estado { get; set; }

        public virtual tbAlumnos Alum { get; set; }
        public virtual tbUsuarios CapA_CreacionNavigation { get; set; }
        public virtual tbUsuarios CapA_ModificacionNavigation { get; set; }
        public virtual tbMaestros Maes { get; set; }
    }
}