// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbMunicipos = new HashSet<tbMunicipos>();
        }

        public string Depa_Id { get; set; }
        public string Depa_Descripcion { get; set; }
        public int? Depa_Creacion { get; set; }
        public DateTime? DePa_FechaCreacion { get; set; }
        public int? Depa_Modificacion { get; set; }
        public DateTime? Depa_FechaModificacion { get; set; }
        public bool? Depa_Estado { get; set; }

        public virtual ICollection<tbMunicipos> tbMunicipos { get; set; }
    }
}