// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbMaestros
    {
        public tbMaestros()
        {
            tbCalificacionPorAlumno = new HashSet<tbCalificacionPorAlumno>();
            tbMaestrosPorCursos = new HashSet<tbMaestrosPorCursos>();
            tbReportesPorMaestros = new HashSet<tbReportesPorMaestros>();
        }

        public int Maes_Id { get; set; }
        public int? Pers_Id { get; set; }
        public int? Maes_Usuario { get; set; }
        public int? Maes_Creacion { get; set; }
        public DateTime? Maes_FechaCreacion { get; set; }
        public int? Maes_Modificacion { get; set; }
        public DateTime? Maes_FechaModificacion { get; set; }
        public bool? Maes_Estado { get; set; }

        public virtual tbUsuarios Maes_CreacionNavigation { get; set; }
        public virtual tbUsuarios Maes_ModificacionNavigation { get; set; }
        public virtual tbUsuarios Maes_UsuarioNavigation { get; set; }
        public virtual tbPersonas Pers { get; set; }
        public virtual ICollection<tbCalificacionPorAlumno> tbCalificacionPorAlumno { get; set; }
        public virtual ICollection<tbMaestrosPorCursos> tbMaestrosPorCursos { get; set; }
        public virtual ICollection<tbReportesPorMaestros> tbReportesPorMaestros { get; set; }
    }
}