// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbMaestrosPorCursos
    {
        public int Macu_Id { get; set; }
        public int? Maes_Id { get; set; }
        public int? Curs_Id { get; set; }
        public int? Mate_Id { get; set; }
        public int? Macu_Creacion { get; set; }
        public DateTime? Macu_FechaCreacion { get; set; }
        public int? Macu_Modificacion { get; set; }
        public DateTime? Macu_FechaModificacion { get; set; }
        public bool? Macu_Estado { get; set; }

        public virtual tbCursos Curs { get; set; }
        public virtual tbUsuarios Macu_CreacionNavigation { get; set; }
        public virtual tbUsuarios Macu_ModificacionNavigation { get; set; }
        public virtual tbMaestros Maes { get; set; }
        public virtual Materia Mate { get; set; }
    }
}