// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbMunicipos
    {
        public tbMunicipos()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public string Muni_Id { get; set; }
        public string Muni_Descripcion { get; set; }
        public string Depa_Id { get; set; }
        public int? Muni_Creacion { get; set; }
        public DateTime? Muni_FechaCreacion { get; set; }
        public int? Muni_Modificacion { get; set; }
        public DateTime? Muni_FechaModificacion { get; set; }
        public int? Muni_Estado { get; set; }

        public virtual tbDepartamentos Depa { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}