// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbParcial
    {
        public tbParcial()
        {
            tbCalificacionPorAlumno = new HashSet<tbCalificacionPorAlumno>();
        }

        public int Parc_Id { get; set; }
        public string Parc_Descripcion { get; set; }
        public DateTime? Parc_Inicio { get; set; }
        public DateTime? Parc_Fin { get; set; }

        public virtual ICollection<tbCalificacionPorAlumno> tbCalificacionPorAlumno { get; set; }
    }
}