// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbPadresPorAlumno
    {
        public int PaAl_Id { get; set; }
        public int? Padr_Id { get; set; }
        public int? Alum_Id { get; set; }
        public int? PaAl_Creacion { get; set; }
        public DateTime? PaAl_FechaCreacion { get; set; }
        public int? PaAl_Modificacion { get; set; }
        public DateTime? PaAl_FechaModificacion { get; set; }
        public bool? PaAl_Estado { get; set; }

        public virtual tbAlumnos Alum { get; set; }
        public virtual tbUsuarios PaAl_CreacionNavigation { get; set; }
        public virtual tbUsuarios PaAl_ModificacionNavigation { get; set; }
        public virtual tbPadres Padr { get; set; }
    }
}