// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbPadres
    {
        public tbPadres()
        {
            tbPadresPorAlumno = new HashSet<tbPadresPorAlumno>();
        }

        public int Padr_Id { get; set; }
        public int? Pers_Id { get; set; }
        public decimal? Padr_Telefono { get; set; }
        public string Padr_Direccion { get; set; }
        public int? Padr_Usuario { get; set; }
        public int? Padr_Creacion { get; set; }
        public DateTime? Padr_FechaCreacion { get; set; }
        public int? Padr_Modificacion { get; set; }
        public DateTime? Padr_FechaModificacion { get; set; }
        public bool? Padr_Estado { get; set; }
        public string Padr_Correo { get; set; }

        public virtual tbUsuarios Padr_CreacionNavigation { get; set; }
        public virtual tbUsuarios Padr_ModificacionNavigation { get; set; }
        public virtual tbUsuarios Padr_UsuarioNavigation { get; set; }
        public virtual tbPersonas Pers { get; set; }
        public virtual ICollection<tbPadresPorAlumno> tbPadresPorAlumno { get; set; }
    }
}