// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbPersonas
    {
        public tbPersonas()
        {
            tbMaestros = new HashSet<tbMaestros>();
            tbPadres = new HashSet<tbPadres>();
        }

        public int Pers_Id { get; set; }
        public string Pers_Identidad { get; set; }
        public string Pers_PrimerNombre { get; set; }
        public string Pers_SegundoNombre { get; set; }
        public string Pers_PrimerApellido { get; set; }
        public string Pers_SegundoApellido { get; set; }
        public string Pers_Sexo { get; set; }
        public int? EsCi_Id { get; set; }
        public string Muni_Id { get; set; }
        public int? Pers_Creacion { get; set; }
        public DateTime? Pers_FechaCreacion { get; set; }
        public int? Pers_Modificacion { get; set; }
        public DateTime? Pers_FechaModificacion { get; set; }
        public bool? Pers_Estado { get; set; }

        public virtual tbEstadosCiviles EsCi { get; set; }
        public virtual tbMunicipos Muni { get; set; }
        public virtual ICollection<tbMaestros> tbMaestros { get; set; }
        public virtual ICollection<tbPadres> tbPadres { get; set; }
    }
}