// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbReportes
    {
        public tbReportes()
        {
            tbReportesPorMaestros = new HashSet<tbReportesPorMaestros>();
        }

        public int Repo_Id { get; set; }
        public string Repo_Descripcion { get; set; }
        public int? Repo_Creacion { get; set; }
        public DateTime? Repo_FechaCreacion { get; set; }
        public int? Repo_Modificacion { get; set; }
        public DateTime? Repo_FechaModificacion { get; set; }
        public bool? Repo_Estado { get; set; }

        public virtual tbUsuarios Repo_CreacionNavigation { get; set; }
        public virtual tbUsuarios Repo_ModificacionNavigation { get; set; }
        public virtual ICollection<tbReportesPorMaestros> tbReportesPorMaestros { get; set; }
    }
}