// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbReportesPorMaestros
    {
        public int Rema_Id { get; set; }
        public int? Repo_Id { get; set; }
        public int? Mate_Id { get; set; }
        public int? Maes_Id { get; set; }
        public int? Alum_Id { get; set; }
        public int? Rema_Creacion { get; set; }
        public DateTime? Rema_FechaCreacion { get; set; }
        public int? Rema_Modificacion { get; set; }
        public DateTime? Rema_FechaModificacion { get; set; }
        public bool? Rema_Estado { get; set; }
        [NotMapped]
        public string Leve { get; set; }

        [NotMapped]
        public string Grave { get; set; }
        [NotMapped]
        public string MuyGrave { get; set; }
        [NotMapped]
        public string Expulsion { get; set; }


        [NotMapped]
        public string Alumno { get; set; }
        [NotMapped]
        public string Repo_Descripcion { get; set; }
        [NotMapped]
        public string Repo_Causa { get; set; }
        [NotMapped]
        public string Mate_Descripcion { get; set; }



        [NotMapped]
        public string Maestro { get; set; }

        [NotMapped]
        public string sexoa { get; set; }


        public virtual tbAlumnos Alum { get; set; }
        public virtual tbMaestros Maes { get; set; }
        public virtual Materia Mate { get; set; }
        public virtual tbUsuarios Rema_CreacionNavigation { get; set; }
        public virtual tbUsuarios Rema_ModificacionNavigation { get; set; }
        public virtual tbReportes Repo { get; set; }
    }
}