// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int Role_Id { get; set; }
        public string Role_Descripcion { get; set; }
        public int? Role_Creacion { get; set; }
        public DateTime? Role_FechaCreacion { get; set; }
        public int? Role_Modificacion { get; set; }
        public DateTime? Role_FechaModificacion { get; set; }
        public bool? Role_Estado { get; set; }

        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}