// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            MateriaMate_CreacionNavigation = new HashSet<Materia>();
            MateriaMate_ModificacionNavigation = new HashSet<Materia>();
            tbAlumnosAlum_CreacionNavigation = new HashSet<tbAlumnos>();
            tbAlumnosAlum_ModificacionNavigation = new HashSet<tbAlumnos>();
            tbCalificacionPorAlumnoCapA_CreacionNavigation = new HashSet<tbCalificacionPorAlumno>();
            tbCalificacionPorAlumnoCapA_ModificacionNavigation = new HashSet<tbCalificacionPorAlumno>();
            tbCursosCurs_CreacionNavigation = new HashSet<tbCursos>();
            tbCursosCurs_ModificacionNavigation = new HashSet<tbCursos>();
            tbMaestrosMaes_CreacionNavigation = new HashSet<tbMaestros>();
            tbMaestrosMaes_ModificacionNavigation = new HashSet<tbMaestros>();
            tbMaestrosMaes_UsuarioNavigation = new HashSet<tbMaestros>();
            tbMaestrosPorCursosMacu_CreacionNavigation = new HashSet<tbMaestrosPorCursos>();
            tbMaestrosPorCursosMacu_ModificacionNavigation = new HashSet<tbMaestrosPorCursos>();
            tbMatriculaMatr_CreacionNavigation = new HashSet<tbMatricula>();
            tbMatriculaMatr_ModificacionNavigation = new HashSet<tbMatricula>();
            tbPadresPadr_CreacionNavigation = new HashSet<tbPadres>();
            tbPadresPadr_ModificacionNavigation = new HashSet<tbPadres>();
            tbPadresPadr_UsuarioNavigation = new HashSet<tbPadres>();
            tbPadresPorAlumnoPaAl_CreacionNavigation = new HashSet<tbPadresPorAlumno>();
            tbPadresPorAlumnoPaAl_ModificacionNavigation = new HashSet<tbPadresPorAlumno>();
            tbReportesPorMaestrosRema_CreacionNavigation = new HashSet<tbReportesPorMaestros>();
            tbReportesPorMaestrosRema_ModificacionNavigation = new HashSet<tbReportesPorMaestros>();
            tbReportesRepo_CreacionNavigation = new HashSet<tbReportes>();
            tbReportesRepo_ModificacionNavigation = new HashSet<tbReportes>();
        }

        public int Usua_Id { get; set; }
        public string Usua_Usuario { get; set; }
        public string Usua_Clave { get; set; }
        public int? Role_Id { get; set; }
        public bool? Usua_EsAdmin { get; set; }
        public int? Usua_Creacion { get; set; }
        public DateTime? Usua_FechaCreacion { get; set; }
        public int? Usua_Modificacion { get; set; }
        public DateTime? Usua_FechaModificacion { get; set; }
        public bool? Usua_Estado { get; set; }

        [NotMapped]
        public string Role_Descripcion { get; set; }

        [NotMapped]
        public string Email { get; set; }

        [NotMapped]
        public string usua_creac { get; set; }

        [NotMapped]
        public string usua_modi { get; set; }

        public virtual tbRoles Role { get; set; }
        public virtual ICollection<Materia> MateriaMate_CreacionNavigation { get; set; }
        public virtual ICollection<Materia> MateriaMate_ModificacionNavigation { get; set; }
        public virtual ICollection<tbAlumnos> tbAlumnosAlum_CreacionNavigation { get; set; }
        public virtual ICollection<tbAlumnos> tbAlumnosAlum_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCalificacionPorAlumno> tbCalificacionPorAlumnoCapA_CreacionNavigation { get; set; }
        public virtual ICollection<tbCalificacionPorAlumno> tbCalificacionPorAlumnoCapA_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCursos> tbCursosCurs_CreacionNavigation { get; set; }
        public virtual ICollection<tbCursos> tbCursosCurs_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMaestros> tbMaestrosMaes_CreacionNavigation { get; set; }
        public virtual ICollection<tbMaestros> tbMaestrosMaes_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMaestros> tbMaestrosMaes_UsuarioNavigation { get; set; }
        public virtual ICollection<tbMaestrosPorCursos> tbMaestrosPorCursosMacu_CreacionNavigation { get; set; }
        public virtual ICollection<tbMaestrosPorCursos> tbMaestrosPorCursosMacu_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMatricula> tbMatriculaMatr_CreacionNavigation { get; set; }
        public virtual ICollection<tbMatricula> tbMatriculaMatr_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPadres> tbPadresPadr_CreacionNavigation { get; set; }
        public virtual ICollection<tbPadres> tbPadresPadr_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPadres> tbPadresPadr_UsuarioNavigation { get; set; }
        public virtual ICollection<tbPadresPorAlumno> tbPadresPorAlumnoPaAl_CreacionNavigation { get; set; }
        public virtual ICollection<tbPadresPorAlumno> tbPadresPorAlumnoPaAl_ModificacionNavigation { get; set; }
        public virtual ICollection<tbReportesPorMaestros> tbReportesPorMaestrosRema_CreacionNavigation { get; set; }
        public virtual ICollection<tbReportesPorMaestros> tbReportesPorMaestrosRema_ModificacionNavigation { get; set; }
        public virtual ICollection<tbReportes> tbReportesRepo_CreacionNavigation { get; set; }
        public virtual ICollection<tbReportes> tbReportesRepo_ModificacionNavigation { get; set; }
    }
}