// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Calificaciones.Entities.Entities
{
    public partial class vw_NotasPorParcial
    {
        public int Alum_Id { get; set; }
        public string Alumno { get; set; }
        public string Materia { get; set; }
        public decimal? Parcial1 { get; set; }
        public decimal? Parcial2 { get; set; }
        public decimal? Parcial3 { get; set; }
    }
}