// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Sistema_Calificaciones.Entities.Entities;

#nullable disable

namespace Sistema_Calificaciones.DataAccess.Context
{
    public partial class BdreportecalificacionesContext : DbContext
    {
        public BdreportecalificacionesContext()
        {
        }

        public BdreportecalificacionesContext(DbContextOptions<BdreportecalificacionesContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<tbAlumnos> tbAlumnos { get; set; }
        public virtual DbSet<tbCalificacionPorAlumno> tbCalificacionPorAlumno { get; set; }
        public virtual DbSet<tbCursos> tbCursos { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbMaestros> tbMaestros { get; set; }
        public virtual DbSet<tbMaestrosPorCursos> tbMaestrosPorCursos { get; set; }
        public virtual DbSet<tbMatricula> tbMatricula { get; set; }
        public virtual DbSet<tbMunicipos> tbMunicipos { get; set; }
        public virtual DbSet<tbPadres> tbPadres { get; set; }
        public virtual DbSet<tbPadresPorAlumno> tbPadresPorAlumno { get; set; }
        public virtual DbSet<tbParcial> tbParcial { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbReportes> tbReportes { get; set; }
        public virtual DbSet<tbReportesPorMaestros> tbReportesPorMaestros { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<vw_NotasPorParcial> vw_NotasPorParcial { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Materia>(entity =>
            {
                entity.HasKey(e => e.Mate_Id)
                    .HasName("PK__Materia__E95FAA0D382EFA38");

                entity.ToTable("Materia", "Repo");

                entity.Property(e => e.Mate_Descripcion).HasMaxLength(50);

                entity.Property(e => e.Mate_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Mate_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Mate_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Mate_CreacionNavigation)
                    .WithMany(p => p.MateriaMate_CreacionNavigation)
                    .HasForeignKey(d => d.Mate_Creacion)
                    .HasConstraintName("FK_tbAlumnosPorCurso_tbUsuarios_Mate_Creacion");

                entity.HasOne(d => d.Mate_ModificacionNavigation)
                    .WithMany(p => p.MateriaMate_ModificacionNavigation)
                    .HasForeignKey(d => d.Mate_Modificacion)
                    .HasConstraintName("FK_tbAlumnosPorCurso_tbUsuarios_Mate_Modificacion");
            });

            modelBuilder.Entity<tbAlumnos>(entity =>
            {
                entity.HasKey(e => e.Alum_Id)
                    .HasName("PK__tbAlumno__D7912C63316926B2");

                entity.ToTable("tbAlumnos", "Repo");

                entity.Property(e => e.Alum_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Alum_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Alum_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Alum_CreacionNavigation)
                    .WithMany(p => p.tbAlumnosAlum_CreacionNavigation)
                    .HasForeignKey(d => d.Alum_Creacion)
                    .HasConstraintName("FK_tbCursos_tbAlumnos_Alum_Creacion");

                entity.HasOne(d => d.Alum_ModificacionNavigation)
                    .WithMany(p => p.tbAlumnosAlum_ModificacionNavigation)
                    .HasForeignKey(d => d.Alum_Modificacion)
                    .HasConstraintName("FK_tbCursos_tbAlumnos_Alum_Modificacion");

                entity.HasOne(d => d.Curs)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Curs_Id)
                    .HasConstraintName("FK_tbtbAlumnosPorCurso_tbCuros_Curs_Id");

                entity.HasOne(d => d.Matr)
                    .WithMany(p => p.tbAlumnos)
                    .HasForeignKey(d => d.Matr_Id)
                    .HasConstraintName("FK_tbCursos_tbMatricula_Matr_Id");
            });

            modelBuilder.Entity<tbCalificacionPorAlumno>(entity =>
            {
                entity.HasKey(e => e.CapA_Id)
                    .HasName("PK__tbCalifi__9DF1E2AB81ACBCC4");

                entity.ToTable("tbCalificacionPorAlumno", "Repo");

                entity.Property(e => e.CapA_Calficacion).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.CapA_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.CapA_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.CapA_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Alum)
                    .WithMany(p => p.tbCalificacionPorAlumno)
                    .HasForeignKey(d => d.Alum_Id)
                    .HasConstraintName("FK_CalificacionPorAlumno_tbAlumnos_Alum_Id");

                entity.HasOne(d => d.CapA_CreacionNavigation)
                    .WithMany(p => p.tbCalificacionPorAlumnoCapA_CreacionNavigation)
                    .HasForeignKey(d => d.CapA_Creacion)
                    .HasConstraintName("FK_CalificacionPorAlumno_tbUsuarios_CapA_Creacion");

                entity.HasOne(d => d.CapA_ModificacionNavigation)
                    .WithMany(p => p.tbCalificacionPorAlumnoCapA_ModificacionNavigation)
                    .HasForeignKey(d => d.CapA_Modificacion)
                    .HasConstraintName("FK_CalificacionPorAlumno_tbUsuarios_CapA_Modificacion");

                entity.HasOne(d => d.Maes)
                    .WithMany(p => p.tbCalificacionPorAlumno)
                    .HasForeignKey(d => d.Maes_Id)
                    .HasConstraintName("FK_CalificacionPorAlumno_tbMestros_Maes_Id");

                entity.HasOne(d => d.Parc)
                    .WithMany(p => p.tbCalificacionPorAlumno)
                    .HasForeignKey(d => d.Parc_Id);
            });

            modelBuilder.Entity<tbCursos>(entity =>
            {
                entity.HasKey(e => e.Curs_Id)
                    .HasName("PK__tbCursos__638C20FA5E68E454");

                entity.ToTable("tbCursos", "Repo");

                entity.Property(e => e.Curs_Descripcion).HasMaxLength(50);

                entity.Property(e => e.Curs_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Curs_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Curs_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Curs_CreacionNavigation)
                    .WithMany(p => p.tbCursosCurs_CreacionNavigation)
                    .HasForeignKey(d => d.Curs_Creacion);

                entity.HasOne(d => d.Curs_ModificacionNavigation)
                    .WithMany(p => p.tbCursosCurs_ModificacionNavigation)
                    .HasForeignKey(d => d.Curs_Modificacion);
            });

            modelBuilder.Entity<tbDepartamentos>(entity =>
            {
                entity.HasKey(e => e.Depa_Id)
                    .HasName("PK__tbDepart__D701E9B5A91BE10E");

                entity.ToTable("tbDepartamentos", "Gene");

                entity.Property(e => e.Depa_Id).HasMaxLength(2);

                entity.Property(e => e.DePa_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Depa_Descripcion).HasMaxLength(50);

                entity.Property(e => e.Depa_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Depa_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbEstadosCiviles>(entity =>
            {
                entity.HasKey(e => e.EsCi_Id)
                    .HasName("PK__tbEstado__6D720574605569FE");

                entity.ToTable("tbEstadosCiviles", "Gene");

                entity.Property(e => e.EsCi_Descripcion).HasMaxLength(50);

                entity.Property(e => e.EsCi_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.EsCi_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.EsCi_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbMaestros>(entity =>
            {
                entity.HasKey(e => e.Maes_Id)
                    .HasName("PK__tbMaestr__BAB4A32DAC606579");

                entity.ToTable("tbMaestros", "Repo");

                entity.Property(e => e.Maes_Correo).IsUnicode(false);

                entity.Property(e => e.Maes_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Maes_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Maes_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Maes_CreacionNavigation)
                    .WithMany(p => p.tbMaestrosMaes_CreacionNavigation)
                    .HasForeignKey(d => d.Maes_Creacion)
                    .HasConstraintName("FK_tbMaestros_Maes_Creacion");

                entity.HasOne(d => d.Maes_ModificacionNavigation)
                    .WithMany(p => p.tbMaestrosMaes_ModificacionNavigation)
                    .HasForeignKey(d => d.Maes_Modificacion)
                    .HasConstraintName("FK_tbMaestros_Maes_Modificacion");

                entity.HasOne(d => d.Maes_UsuarioNavigation)
                    .WithMany(p => p.tbMaestrosMaes_UsuarioNavigation)
                    .HasForeignKey(d => d.Maes_Usuario)
                    .HasConstraintName("FK_tbMaestros_Maes_Usuario");

                entity.HasOne(d => d.Pers)
                    .WithMany(p => p.tbMaestros)
                    .HasForeignKey(d => d.Pers_Id)
                    .HasConstraintName("FK_tbMaestros_Pers_Id");
            });

            modelBuilder.Entity<tbMaestrosPorCursos>(entity =>
            {
                entity.HasKey(e => e.Macu_Id)
                    .HasName("PK__tbMaestr__CD9D2EDFC2399602");

                entity.ToTable("tbMaestrosPorCursos", "Repo");

                entity.Property(e => e.Macu_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Macu_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Macu_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Curs)
                    .WithMany(p => p.tbMaestrosPorCursos)
                    .HasForeignKey(d => d.Curs_Id)
                    .HasConstraintName("FK_tbMaestrosPorCursos_Curs_Id");

                entity.HasOne(d => d.Macu_CreacionNavigation)
                    .WithMany(p => p.tbMaestrosPorCursosMacu_CreacionNavigation)
                    .HasForeignKey(d => d.Macu_Creacion)
                    .HasConstraintName("FK_tbMaestrosPorCursos_Macu_Creacion");

                entity.HasOne(d => d.Macu_ModificacionNavigation)
                    .WithMany(p => p.tbMaestrosPorCursosMacu_ModificacionNavigation)
                    .HasForeignKey(d => d.Macu_Modificacion)
                    .HasConstraintName("FK_tbMaestrosPorCursos_Macu_Modificacion");

                entity.HasOne(d => d.Maes)
                    .WithMany(p => p.tbMaestrosPorCursos)
                    .HasForeignKey(d => d.Maes_Id)
                    .HasConstraintName("FK_tbMaestrosPorCursos_Maes_id");

                entity.HasOne(d => d.Mate)
                    .WithMany(p => p.tbMaestrosPorCursos)
                    .HasForeignKey(d => d.Mate_Id)
                    .HasConstraintName("FK_tbMaestrosPorCursos_Mate_Id");
            });

            modelBuilder.Entity<tbMatricula>(entity =>
            {
                entity.HasKey(e => e.Matr_Id)
                    .HasName("PK__tbMatric__7F340847790D3358");

                entity.ToTable("tbMatricula", "Repo");

                entity.Property(e => e.MatrPeri_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Matr_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Matr_FechaFinalizacion).HasColumnType("datetime");

                entity.Property(e => e.Matr_FechaInicio).HasColumnType("datetime");

                entity.Property(e => e.Matr_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Matr_CreacionNavigation)
                    .WithMany(p => p.tbMatriculaMatr_CreacionNavigation)
                    .HasForeignKey(d => d.Matr_Creacion)
                    .HasConstraintName("FK_tbPeriodo_tbUsuarios_Matr_Creacion");

                entity.HasOne(d => d.Matr_ModificacionNavigation)
                    .WithMany(p => p.tbMatriculaMatr_ModificacionNavigation)
                    .HasForeignKey(d => d.Matr_Modificacion)
                    .HasConstraintName("FK_tbPeriodo_tbUsuarios_Matr_Modificacion");
            });

            modelBuilder.Entity<tbMunicipos>(entity =>
            {
                entity.HasKey(e => e.Muni_Id)
                    .HasName("PK__tbMunici__6B07AA3C4D6400F2");

                entity.ToTable("tbMunicipos", "Gene");

                entity.Property(e => e.Muni_Id).HasMaxLength(4);

                entity.Property(e => e.Depa_Id).HasMaxLength(2);

                entity.Property(e => e.Muni_Descripcion).HasMaxLength(50);

                entity.Property(e => e.Muni_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Muni_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Muni_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Depa)
                    .WithMany(p => p.tbMunicipos)
                    .HasForeignKey(d => d.Depa_Id)
                    .HasConstraintName("FK_Ciudades_Departamentos_Depa_Id");
            });

            modelBuilder.Entity<tbPadres>(entity =>
            {
                entity.HasKey(e => e.Padr_Id)
                    .HasName("PK__tbPadres__3F2B305EB03717D3");

                entity.ToTable("tbPadres", "Repo");

                entity.Property(e => e.Padr_Correo).IsUnicode(false);

                entity.Property(e => e.Padr_Direccion).HasMaxLength(50);

                entity.Property(e => e.Padr_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Padr_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Padr_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Padr_Telefono).HasColumnType("numeric(18, 0)");

                entity.HasOne(d => d.Padr_CreacionNavigation)
                    .WithMany(p => p.tbPadresPadr_CreacionNavigation)
                    .HasForeignKey(d => d.Padr_Creacion);

                entity.HasOne(d => d.Padr_ModificacionNavigation)
                    .WithMany(p => p.tbPadresPadr_ModificacionNavigation)
                    .HasForeignKey(d => d.Padr_Modificacion);

                entity.HasOne(d => d.Padr_UsuarioNavigation)
                    .WithMany(p => p.tbPadresPadr_UsuarioNavigation)
                    .HasForeignKey(d => d.Padr_Usuario)
                    .HasConstraintName("FK_tbPadres_Padr_Usuario");

                entity.HasOne(d => d.Pers)
                    .WithMany(p => p.tbPadres)
                    .HasForeignKey(d => d.Pers_Id)
                    .HasConstraintName("FK_tbPersonas_tbPadres_Pers_Id");
            });

            modelBuilder.Entity<tbPadresPorAlumno>(entity =>
            {
                entity.HasKey(e => e.PaAl_Id)
                    .HasName("PK__tbPadres__5CD36859CD2FCC8F");

                entity.ToTable("tbPadresPorAlumno", "Repo");

                entity.Property(e => e.PaAl_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.PaAl_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.PaAl_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Alum)
                    .WithMany(p => p.tbPadresPorAlumno)
                    .HasForeignKey(d => d.Alum_Id);

                entity.HasOne(d => d.PaAl_CreacionNavigation)
                    .WithMany(p => p.tbPadresPorAlumnoPaAl_CreacionNavigation)
                    .HasForeignKey(d => d.PaAl_Creacion)
                    .HasConstraintName("FK_tbCursos_tbUsuarios_PaAl_Creacion");

                entity.HasOne(d => d.PaAl_ModificacionNavigation)
                    .WithMany(p => p.tbPadresPorAlumnoPaAl_ModificacionNavigation)
                    .HasForeignKey(d => d.PaAl_Modificacion)
                    .HasConstraintName("FK_tbCursos_tbUsuarios_PaAl_Modificacion");

                entity.HasOne(d => d.Padr)
                    .WithMany(p => p.tbPadresPorAlumno)
                    .HasForeignKey(d => d.Padr_Id);
            });

            modelBuilder.Entity<tbParcial>(entity =>
            {
                entity.HasKey(e => e.Parc_Id);

                entity.ToTable("tbParcial", "Repo");

                entity.Property(e => e.Parc_Id).ValueGeneratedNever();

                entity.Property(e => e.Parc_Descripcion)
                    .HasMaxLength(50)
                    .IsFixedLength(true);

                entity.Property(e => e.Parc_Fin).HasColumnType("date");

                entity.Property(e => e.Parc_Inicio).HasColumnType("date");
            });

            modelBuilder.Entity<tbPersonas>(entity =>
            {
                entity.HasKey(e => e.Pers_Id)
                    .HasName("PK__tbPerson__B246CCB8247EB2F1");

                entity.ToTable("tbPersonas", "Gene");

                entity.HasIndex(e => e.Pers_Identidad, "UQ__tbPerson__AD277399849DDF35")
                    .IsUnique();

                entity.Property(e => e.Muni_Id).HasMaxLength(4);

                entity.Property(e => e.Pers_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Pers_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Pers_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Pers_Identidad)
                    .IsRequired()
                    .HasMaxLength(13);

                entity.Property(e => e.Pers_PrimerApellido).HasMaxLength(50);

                entity.Property(e => e.Pers_PrimerNombre).HasMaxLength(50);

                entity.Property(e => e.Pers_SegundoApellido).HasMaxLength(50);

                entity.Property(e => e.Pers_SegundoNombre).HasMaxLength(50);

                entity.Property(e => e.Pers_Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.HasOne(d => d.EsCi)
                    .WithMany(p => p.tbPersonas)
                    .HasForeignKey(d => d.EsCi_Id);

                entity.HasOne(d => d.Muni)
                    .WithMany(p => p.tbPersonas)
                    .HasForeignKey(d => d.Muni_Id)
                    .HasConstraintName("FK_tbPersonas_tbMunicipios_Muni_Id");
            });

            modelBuilder.Entity<tbReportes>(entity =>
            {
                entity.HasKey(e => e.Repo_Id)
                    .HasName("PK__tbReport__AFE29E84EB532E93");

                entity.ToTable("tbReportes", "Repo");

                entity.Property(e => e.Repo_Descripcion).IsUnicode(false);

                entity.Property(e => e.Repo_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Repo_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Repo_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Repo_CreacionNavigation)
                    .WithMany(p => p.tbReportesRepo_CreacionNavigation)
                    .HasForeignKey(d => d.Repo_Creacion)
                    .HasConstraintName("FK_tbReportes_Repo_Creacion");

                entity.HasOne(d => d.Repo_ModificacionNavigation)
                    .WithMany(p => p.tbReportesRepo_ModificacionNavigation)
                    .HasForeignKey(d => d.Repo_Modificacion)
                    .HasConstraintName("FK_tbReportes_Repo_Modificacion");
            });

            modelBuilder.Entity<tbReportesPorMaestros>(entity =>
            {
                entity.HasKey(e => e.Rema_Id)
                    .HasName("PK__tbReport__702DE9489F1D2EC8");

                entity.ToTable("tbReportesPorMaestros", "Repo");

                entity.Property(e => e.Rema_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Rema_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Rema_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Repo_Causa)
                    .HasMaxLength(200)
                    .IsFixedLength(true);

                entity.HasOne(d => d.Alum)
                    .WithMany(p => p.tbReportesPorMaestros)
                    .HasForeignKey(d => d.Alum_Id)
                    .HasConstraintName("FK_tbReportesPorMaestros_Alum_Id");

                entity.HasOne(d => d.Maes)
                    .WithMany(p => p.tbReportesPorMaestros)
                    .HasForeignKey(d => d.Maes_Id)
                    .HasConstraintName("FK_tbReportesPorMaestros_Maes_Id");

                entity.HasOne(d => d.Mate)
                    .WithMany(p => p.tbReportesPorMaestros)
                    .HasForeignKey(d => d.Mate_Id)
                    .HasConstraintName("FK_tbReportesPorMaestros_tbMateria");

                entity.HasOne(d => d.Rema_CreacionNavigation)
                    .WithMany(p => p.tbReportesPorMaestrosRema_CreacionNavigation)
                    .HasForeignKey(d => d.Rema_Creacion)
                    .HasConstraintName("FK_tbReportesPorMaestros_Rema_Creacion");

                entity.HasOne(d => d.Rema_ModificacionNavigation)
                    .WithMany(p => p.tbReportesPorMaestrosRema_ModificacionNavigation)
                    .HasForeignKey(d => d.Rema_Modificacion)
                    .HasConstraintName("FK_tbReportesPorMaestros_Rema_Modificacion");

                entity.HasOne(d => d.Repo)
                    .WithMany(p => p.tbReportesPorMaestros)
                    .HasForeignKey(d => d.Repo_Id)
                    .HasConstraintName("FK_tbReportesPorMaestros_Repo_Id");
            });

            modelBuilder.Entity<tbRoles>(entity =>
            {
                entity.HasKey(e => e.Role_Id)
                    .HasName("PK__tbRoles__D80AB4BB9825DBD5");

                entity.ToTable("tbRoles", "Acce");

                entity.Property(e => e.Role_Descripcion).HasMaxLength(50);

                entity.Property(e => e.Role_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Role_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Role_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbUsuarios>(entity =>
            {
                entity.HasKey(e => e.Usua_Id)
                    .HasName("PK__tbUsuari__E863C8EED072B629");

                entity.ToTable("tbUsuarios", "Acce");

                entity.HasIndex(e => e.Usua_Usuario, "UQ_tbUsuarios_Usua_Usuario")
                    .IsUnique();

                entity.Property(e => e.Usua_Clave).IsUnicode(false);

                entity.Property(e => e.Usua_Codigo).IsUnicode(false);

                entity.Property(e => e.Usua_Email).IsUnicode(false);

                entity.Property(e => e.Usua_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Usua_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Usua_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Usua_Usuario).HasMaxLength(50);

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.tbUsuarios)
                    .HasForeignKey(d => d.Role_Id);
            });

            modelBuilder.Entity<vw_NotasPorParcial>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vw_NotasPorParcial", "Repo");

                entity.Property(e => e.Alumno).HasMaxLength(101);

                entity.Property(e => e.Materia).HasMaxLength(50);

                entity.Property(e => e.Parcial1).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.Parcial2).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.Parcial3).HasColumnType("numeric(18, 0)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}